PROGRAM	=	matrix_solv_gauss
OBJS	=	gauss.o global_variable.o malloc.o main.o
SRCS	=	$(OBJS:%.o=%.c)
CC	=	gcc
CFLAGS	= -g -Wall
LDFLAGS	=

$(PROGRAM):$(OBJS)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(PROGRAM) $(OBJS) $(LDLIBS) -lm